import { HttpClient } from '@angular/common/http';
import { Injectable, computed, inject, signal } from '@angular/core';
import { firstValueFrom } from 'rxjs';
import type { DemoConfigFile, DemoUser } from '../models/demo-user.model';

/**
 * Runtime configuration, loaded once before the app renders.
 *
 * Deliberately runtime rather than build-time: `public/demo-config.json` is generated by
 * `npm run setup`, so the app picks up whatever cast and API key were seeded without a
 * rebuild. It carries user tokens, which is a demo-only shortcut - a real app hands the SDK
 * a token provider instead (see README).
 */
@Injectable({ providedIn: 'root' })
export class DemoConfig {
  private readonly http = inject(HttpClient);
  private readonly config = signal<DemoConfigFile | null>(null);

  readonly loaded = computed(() => this.config() !== null);
  readonly users = computed<DemoUser[]>(() => this.config()?.users ?? []);
  readonly proctors = computed(() => this.users().filter((u) => u.role === 'proctor'));
  readonly students = computed(() => this.users().filter((u) => u.role === 'student'));
  readonly generatedAt = computed(() => this.config()?.generatedAt ?? null);

  get apiKey(): string {
    const key = this.config()?.apiKey;
    if (!key) throw new Error('DemoConfig used before it finished loading.');
    return key;
  }

  /** Called by `provideAppInitializer`, so the app never renders without config. */
  async load(): Promise<void> {
    try {
      const file = await firstValueFrom(
        this.http.get<DemoConfigFile>('demo-config.json'),
      );
      if (!file?.apiKey || !file.users?.length) {
        throw new Error('demo-config.json is present but empty or malformed.');
      }
      this.config.set(file);
    } catch (cause) {
      // Nothing works without this, so fail loudly with the fix rather than
      // letting every downstream call produce its own confusing error.
      throw new Error(
        'Could not load demo-config.json. Run `npm run setup` from the repo root first.',
        { cause },
      );
    }
  }

  byId(id: string): DemoUser | undefined {
    return this.users().find((u) => u.id === id);
  }
}
